# Generated by Django 3.2 on 2022-02-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='слаг'),
        ),
    ]
